
package cn.org.hb.back.jws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HbcaService", targetNamespace = "http://jws.back.hb.org.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HbcaService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.HelloResponse")
    public String hello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTimeStamp", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.CreateTimeStamp")
    @ResponseWrapper(localName = "createTimeStampResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.CreateTimeStampResponse")
    public String createTimeStamp(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTimeStampRequest", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.CreateTimeStampRequest")
    @ResponseWrapper(localName = "createTimeStampRequestResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.CreateTimeStampRequestResponse")
    public String createTimeStampRequest(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "genRandom", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GenRandom")
    @ResponseWrapper(localName = "genRandomResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GenRandomResponse")
    public String genRandom();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerCert", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GetServerCert")
    @ResponseWrapper(localName = "getServerCertResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GetServerCertResponse")
    public String getServerCert();

    /**
     * 
     * @param inData
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signData", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignData")
    @ResponseWrapper(localName = "signDataResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataResponse")
    public String signData(
            @WebParam(name = "inData", targetNamespace = "")
                    String inData);

    /**
     * 
     * @param bstrCert
     * @param signedData
     * @param inData
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyCertAndSignedData", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyCertAndSignedData")
    @ResponseWrapper(localName = "verifyCertAndSignedDataResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyCertAndSignedDataResponse")
    public int verifyCertAndSignedData(
            @WebParam(name = "bstrCert", targetNamespace = "")
                    String bstrCert,
            @WebParam(name = "inData", targetNamespace = "")
                    String inData,
            @WebParam(name = "signedData", targetNamespace = "")
                    String signedData);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifySignedData", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifySignedData")
    @ResponseWrapper(localName = "verifySignedDataResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifySignedDataResponse")
    public int verifySignedData(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyTimeStamp", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyTimeStamp")
    @ResponseWrapper(localName = "verifyTimeStampResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyTimeStampResponse")
    public int verifyTimeStamp(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSealImage", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GetSealImage")
    @ResponseWrapper(localName = "getSealImageResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GetSealImageResponse")
    public String getSealImage(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signDataP7Detach", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataP7Detach")
    @ResponseWrapper(localName = "signDataP7DetachResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataP7DetachResponse")
    public String signDataP7Detach(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyDetachSignData", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyDetachSignData")
    @ResponseWrapper(localName = "verifyDetachSignDataResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyDetachSignDataResponse")
    public String verifyDetachSignData(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerCertEx", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GetServerCertEx")
    @ResponseWrapper(localName = "getServerCertExResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.GetServerCertExResponse")
    public String getServerCertEx(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signDataEx", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataEx")
    @ResponseWrapper(localName = "signDataExResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataExResponse")
    public String signDataEx(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signDataByteEx", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataByteEx")
    @ResponseWrapper(localName = "signDataByteExResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataByteExResponse")
    public String signDataByteEx(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    byte[] arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "signDataByteEx_raw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signDataByteEx_raw", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataByteExRaw")
    @ResponseWrapper(localName = "signDataByteEx_rawResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.SignDataByteExRawResponse")
    public String signDataByteExRaw(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    byte[] arg1);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyDetachSignDataEx", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyDetachSignDataEx")
    @ResponseWrapper(localName = "verifyDetachSignDataExResponse", targetNamespace = "http://jws.back.hb.org.cn/", className = "cn.org.hb.back.jws.VerifyDetachSignDataExResponse")
    public String verifyDetachSignDataEx(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    boolean arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    boolean arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    boolean arg4);

}
