
package cn.org.hb.back.jws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HbcaServiceService", targetNamespace = "http://jws.back.hb.org.cn/", wsdlLocation = "http://221.232.224.75:8082/hbcaDSS/hbcaService?wsdl")
public class HbcaServiceService
    extends Service
{

    private final static URL HBCASERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(HbcaServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = HbcaServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://221.232.224.75:8082/hbcaDSS/hbcaService?wsdl");
//            url = new URL(baseUrl, "http://127.0.0.1:8080/hbcaDSS/hbcaService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/hbcaDSS/hbcaService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HBCASERVICESERVICE_WSDL_LOCATION = url;
    }

    public HbcaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HbcaServiceService() {
        super(HBCASERVICESERVICE_WSDL_LOCATION, new QName("http://jws.back.hb.org.cn/", "HbcaServiceService"));
    }

    /**
     * 
     * @return
     *     returns HbcaService
     */
    @WebEndpoint(name = "HbcaServicePort")
    public HbcaService getHbcaServicePort() {
        return super.getPort(new QName("http://jws.back.hb.org.cn/", "HbcaServicePort"), HbcaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HbcaService
     */
    @WebEndpoint(name = "HbcaServicePort")
    public HbcaService getHbcaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jws.back.hb.org.cn/", "HbcaServicePort"), HbcaService.class, features);
    }

}
